# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category', models.IntegerField(choices=[(1, 'GENERAL'), (2, 'PRIMARY'), (3, 'SPECIAL')], db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('party', models.CharField(choices=[('C', 'CONSTITUTION'), ('D', 'DEMOCRAT'), ('E', 'REFORM'), ('G', 'GREEN'), ('L', 'LIBERTARIAN'), ('N', 'NATURAL_LAW'), ('R', 'REPUBLICAN'), ('S', 'SOCIALIST'), ('X', 'N/A')], db_index=True, max_length=512)),
            ],
            options={
                'ordering': ('-date', 'party'),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='ohiovoter.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('sos_voterid', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('county_number', models.IntegerField(null=True)),
                ('county_id', models.CharField(max_length=512, null=True)),
                ('last_name', models.CharField(max_length=512, null=True)),
                ('first_name', models.CharField(max_length=512, null=True)),
                ('middle_name', models.CharField(max_length=512, null=True)),
                ('suffix', models.CharField(max_length=512, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('registration_date', models.DateField(null=True)),
                ('voter_status', models.CharField(max_length=512, null=True)),
                ('party_affiliation', models.CharField(max_length=512, null=True)),
                ('residential_address1', models.CharField(max_length=512, null=True)),
                ('residential_secondary_addr', models.CharField(max_length=512, null=True)),
                ('residential_city', models.CharField(max_length=512, null=True)),
                ('residential_state', models.CharField(max_length=512, null=True)),
                ('residential_zip', models.CharField(max_length=512, null=True)),
                ('residential_zip_plus4', models.CharField(max_length=512, null=True)),
                ('residential_country', models.CharField(max_length=512, null=True)),
                ('residential_postalcode', models.CharField(max_length=512, null=True)),
                ('mailing_address1', models.CharField(max_length=512, null=True)),
                ('mailing_secondary_address', models.CharField(max_length=512, null=True)),
                ('mailing_city', models.CharField(max_length=512, null=True)),
                ('mailing_state', models.CharField(max_length=512, null=True)),
                ('mailing_zip', models.CharField(max_length=512, null=True)),
                ('mailing_zip_plus4', models.CharField(max_length=512, null=True)),
                ('mailing_country', models.CharField(max_length=512, null=True)),
                ('mailing_postal_code', models.CharField(max_length=512, null=True)),
                ('career_center', models.CharField(max_length=512, null=True)),
                ('city', models.CharField(max_length=512, null=True)),
                ('city_school_district', models.CharField(max_length=512, null=True)),
                ('county_court_district', models.CharField(max_length=512, null=True)),
                ('congressional_district', models.IntegerField(null=True)),
                ('court_of_appeals', models.CharField(max_length=512, null=True)),
                ('edu_service_center_district', models.CharField(max_length=512, null=True)),
                ('exempted_vill_school_district', models.CharField(max_length=512, null=True)),
                ('library', models.CharField(max_length=512, null=True)),
                ('local_school_district', models.CharField(max_length=512, null=True)),
                ('municipal_court_district', models.CharField(max_length=512, null=True)),
                ('precinct_name', models.CharField(max_length=512, null=True)),
                ('precinct_code', models.CharField(max_length=512, null=True)),
                ('state_board_of_education', models.CharField(max_length=512, null=True)),
                ('state_representative_district', models.IntegerField(null=True)),
                ('state_senate_district', models.IntegerField(null=True)),
                ('township', models.CharField(max_length=512, null=True)),
                ('village', models.CharField(max_length=512, null=True)),
                ('ward', models.CharField(max_length=512, null=True)),
                ('county', models.CharField(max_length=512, null=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'middle_name'),
            },
        ),
        migrations.AddField(
            model_name='participation',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='ohiovoter.Voter'),
        ),
        migrations.AlterUniqueTogether(
            name='election',
            unique_together=set([('category', 'date', 'party')]),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('election', 'voter')]),
        ),
    ]
