# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohiovoter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='voter',
            name='elections',
        ),
        migrations.AlterField(
            model_name='election',
            name='category',
            field=models.IntegerField(choices=[(1, 'GENERAL'), (2, 'PRIMARY'), (3, 'SPECIAL')], db_index=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='party',
            field=models.CharField(choices=[('C', 'CONSTITUTION'), ('D', 'DEMOCRAT'), ('E', 'REFORM'), ('G', 'GREEN'), ('L', 'LIBERTARIAN'), ('N', 'NATURAL_LAW'), ('R', 'REPUBLICAN'), ('S', 'SOCIALIST'), ('X', 'N/A')], db_index=True, max_length=512),
        ),
        migrations.AddField(
            model_name='participation',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='ohiovoter.Election'),
        ),
        migrations.AddField(
            model_name='participation',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='ohiovoter.Voter'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set([('election', 'voter')]),
        ),
    ]
